// examples/vue/src/components/ProjectList.vue
<script setup lang="ts">
/**
 * Freelo SDK - Vue Component Example
 *
 * Component for displaying a list of projects.
 */

import { ref, onMounted } from 'vue';
import { Freelo, type ProjectWithTasklists, FreeloApiError } from '@freelo/js-sdk';

const freelo = new Freelo({
  email: import.meta.env.VITE_FREELO_EMAIL,
  apiKey: import.meta.env.VITE_FREELO_API_KEY,
  userAgent: 'VueApp/1.0',
});

const projects = ref<ProjectWithTasklists[]>([]);
const loading = ref(true);
const error = ref<string | null>(null);

async function fetchProjects() {
  loading.value = true;
  error.value = null;

  try {
    projects.value = await freelo.projects.list();
  } catch (e) {
    if (e instanceof FreeloApiError) {
      error.value = `API Error: ${e.message}`;
    } else {
      error.value = e instanceof Error ? e.message : 'Failed to fetch projects';
    }
  } finally {
    loading.value = false;
  }
}

onMounted(fetchProjects);
</script>

<template>
  <div class="project-list">
    <div v-if="loading" class="loading">Loading projects...</div>

    <div v-else-if="error" class="error">
      <p>Error: {{ error }}</p>
      <button @click="fetchProjects">Retry</button>
    </div>

    <div v-else-if="projects.length === 0" class="empty">
      No projects found.
    </div>

    <div v-else>
      <h2>Projects ({{ projects.length }})</h2>
      <ul>
        <li v-for="project in projects" :key="project.id" class="project-item">
          <h3>{{ project.name }}</h3>
          <ul v-if="project.tasklists?.length" class="tasklist-list">
            <li v-for="tasklist in project.tasklists" :key="tasklist.id">
              {{ tasklist.name }}
            </li>
          </ul>
        </li>
      </ul>
      <button @click="fetchProjects">Refresh</button>
    </div>
  </div>
</template>

<style scoped>
.project-list {
  padding: 1rem;
}

.project-item {
  margin-bottom: 1rem;
  padding: 0.5rem;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.project-item h3 {
  margin: 0 0 0.5rem 0;
}

.tasklist-list {
  margin-left: 1rem;
  color: #666;
}

.loading,
.empty {
  color: #666;
  font-style: italic;
}

.error {
  color: #c00;
}

button {
  margin-top: 1rem;
  padding: 0.5rem 1rem;
  cursor: pointer;
}
</style>

// examples/react/src/components/ProjectList.tsx
/**
 * Freelo SDK - React Component Example
 *
 * Component for displaying a list of projects.
 */

import { useProjects } from '../hooks/useProjects';

export function ProjectList() {
  const { projects, loading, error, refetch } = useProjects();

  if (loading) {
    return <div className="loading">Loading projects...</div>;
  }

  if (error) {
    return (
      <div className="error">
        <p>Error: {error.message}</p>
        <button onClick={refetch}>Retry</button>
      </div>
    );
  }

  if (projects.length === 0) {
    return <div className="empty">No projects found.</div>;
  }

  return (
    <div className="project-list">
      <h2>Projects ({projects.length})</h2>
      <ul>
        {projects.map((project) => (
          <li key={project.id} className="project-item">
            <h3>{project.name}</h3>
            {project.tasklists && project.tasklists.length > 0 && (
              <ul className="tasklist-list">
                {project.tasklists.map((tasklist) => (
                  <li key={tasklist.id}>{tasklist.name}</li>
                ))}
              </ul>
            )}
          </li>
        ))}
      </ul>
      <button onClick={refetch}>Refresh</button>
    </div>
  );
}
